config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions'
	}
	get 'welcome/index'
	root 'welcome#index'
	# get 'users/show'
	# get 'users/edit'
	put 'users/update_profile_pic'
	get 'users/update_profile_pic'
	get 'users/states'
	get 'states/index'
	resources :users do
		member do
			get :secure_image
		end
	end
	get 'countries/new'
	post 'countries/create'
	get 'places/new'
	post 'places/create'
	get 'places/index'
	get 'places/show'
	get 'places/distance'
	resources :places,only:[:search] do
	  collection do
	    get :search
	  end
	end
	get 'packages/new'
	post 'packages/create'
	get 'packages/index'
	get 'packages/conversion'
	get 'packages/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversion_rate.rb
class ConversionRate < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :places
end

app/models/package.rb
class Package < ApplicationRecord
end

app/models/place.rb
require 'elasticsearch/model'

class Place < ApplicationRecord
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks
	settings do
    mappings dynamic: false do
      indexes :place_name, type: :text
      indexes :place_description, type: :text, analyzer: :english
      indexes :country, type: :text, analyzer: :english
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
					:recoverable, :rememberable, :validatable,
					:confirmable, :lockable, :timeoutable, :trackable

		# validation for first name 
		validates :first_name, presence: true,format: { with: /\A[a-zA-Z]+\z/,message: "must be in alphabets" }
		# validation for last name
		validates :last_name,presence: true,format: { with: /\A[a-zA-Z]+\z/,message: "must be in alphabets " }
		# validation for phone number
		validates :phone_number,numericality: { only_integer: true },presence: true,:length => { :minimum => 10, :maximum => 15 }
		# validation for country 
		validates :country, presence: true
		# validation for state
		validates :state, presence: true
		# validation for address
		validates :address,presence: true

		# image uploading using paperclip    
		attr_accessor :avatar
		has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
		do_not_validate_attachment_file_type :avatar
		# image uploading using active storage
		has_one_attached :image, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	def new
		@country = Country.new
	end
	def create
		@country =Country.new(params.permit(:country))
		@country.save
		redirect_to countries_new_path,notice: "created successfully"
	end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
	def new
		@package =Package.new
	end
	# creation of package
	def create
		@package = Package.new(package_params)
		@package.package_places = params[:package_places]
		@package.save
	end
	# displaying index
	def index
		@packages=Package.all
	end
	# conversion of currency
	def conversion
		@package = Package.find(params[:id])
		# conversion using concurrency gem from USD to selected currency 
		@value =Concurrency.convert(@package.price,params[:currency] )
		# sending response 
		respond_to do |format|
			format.json {render :json=>@value.round(2)}
		end
	end
	# displaying the package details
	def show
		@package= Package.find(params[:id])
	end
	private
	def package_params
		params.permit(:package_places,:price)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user! ,except: [:index]
	def new
		@place = Place.new
	end
	# creation of a place
	def create
		@place = Place.new(place_params)
		@place.save
		redirect_to places_new_path,notice:"created successfully"
	end
	# displaying places
	def index
		# searching for records 
		query = params[:search_places].presence && params[:search_places][:query]
		if query !=nil
			# for displaying records of seach using elastic search 
			@places = Place.__elasticsearch__.search(query).records
		else
			@places = Place.all
		end

	end
	# calculating distance between cities
	def distance
		@city1 = params[:city1]
		@city2 = params[:city2]
		# calculating distance between selected places
		@distance = Geocoder::Calculations.distance_between(@city1,@city2)
		#checking if the distance is provided or not
		if @distance.nan?
			respond_to do |format|
				format.json {render :json=>"not provided for this location"}
			end
		else
			respond_to do |format|
				format.json {render :json=>@distance.round(2)}
			end
		end
	end
	# displaying place details
	def show
		@place= Place.find(params[:id])
	end

	private

	def place_params
		params.permit(:country,:place_name,:place_description)
	end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
	# displaying states as per country
  def index
    @states = CS.states(params[:country])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except:[:states]
	before_action :set_user, except:[:states]
	# for updating profile pictures
	def update_profile_pic
		if request.put?
			# checking if image is present
			if params[:user][:avatar].present?
				@user.avatar = params[:user][:avatar]
			end
			# checking if image is present
			if params[:user][:image].present?
				@user.image = params[:user][:image]
			end
			@user.save!
		end
	end
	# displaying paperclip image
	def secure_image
		send_file current_user.avatar.path
	end
	# setting user before action
	def set_user
		@user = User.find(current_user.id)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/countries/new.html.erb
<div>
<section class="pt-5 pb-5 mt-0 align-items-center d-flex bg-secondary text-white" style="height:50vh;"> 
<div class="container-fluid">
	<%=form_with(url: countries_create_path, method: "post") do |form|%>
<div class="row  justify-content-center align-items-center d-flex text-center ">
    <div class="col-4">
<%=form.text_field :country,placeholder:"country name",class: "form-control"%>

<%=form.submit "submit",class:"btn btn-success" %>

</div>
</div>

<%end%>
</div>
</section>
</div>

app/views/places/distance.html.erb
<div class="container ">
<h3>The distance between <%=@city1%> and <%=@city2%> is <%=@distance.round(2)%>KM</h3>
</div>

app/views/places/index.html.erb
<div class="container">

	<form class="form-inline my-2 my-lg-0">
		<%= form_for :search_places, url: search_places_path, method: :get do |form| %>
			<%= form.text_field :query, value: params[:search_places].presence && params[:search_places][:query],class:"form-control mr-lg-8",placeholder:"search" %>
			<%= form.submit 'Search',class:"btn btn-outline-success my-2 my-sm-0" %>
		<% end %>
	</form>

	<br>

	<div class="row">
		<div class="col">
			<% if @places.empty?  %>
				<h2>No places found matching your query.</h2>
			<% else %>
				<div class="card-columns">
				<% @places.each do |place|%>
				<div class="card p-3 divname">
				<div class="card-header bg-transparent border-success">
						<%= place.country%>
					</div>
					<div class="card-body">
					<h5 class="card-title"><%= place.place_name%></h5>
					<p class="card-text"><%= place.place_description[0..75]%></p>
							<%=link_to "show details",places_show_path(:id=>place.id),class:"btn btn-info "%>
					</div>
				</div>
					<%end%>
				</div>
			<%end%>
		</div>
	</div>
</div>			

app/views/places/new.html.erb
<%=form_with(url: places_create_path, method: "post") do |form|%>
<%#= form.select :country, collection: CountryStateSelect.countries_collection %>
  <%= form.country_select :country %>

<div>
<%=form.text_field :place_name,placeholder:"place name"%>
</div>
<div>
<%=form.text_area :place_description,placeholder:"place description"%>
</div>
<%=form.submit "submit",class:"btn btn-success" %>
<%end%>

app/views/places/search.html.erb
<%= form_for :search_places, url: search_places_path, method: :get do |form| %>
	<%= form.text_field :query, value: params[:search_places].presence && params[:search_places][:query] %>
	<%= form.submit 'Search' %>
<% end %>
<% unless @places.nil? %>
	<% if @places.empty? %>
	<h2>No places found matching your query.</h2>
	<% else %>
	<h2>Search results</h2>

	<table style="width: 100%;">
		<thead>
		 <tr>
			 <th>place</th>
			 <th>description</th>
			 <th>country</th>
		 </tr>
		</thead>

		<tbody>
		<% @places.each do |place| %>
			<tr>
			<td><%= place.place_name %></td>
			<td><%= place.place_description %></td>
			<td><%= place.country %></td>
			</tr>
		<% end %>
		<tbody>
	</table>
	<% end %>
<% end %>

app/views/places/show.html.erb
<div class="container">
	<h1><center><%=@place.country%></center></h1>
	<h4><%=@place.place_name%></h4>
	<p><%=@place.place_description%></p>
		<%=form_with(url: users_states_path, method: "get") do |form|%>
			<div id="city1">
				<%= form.select :city,CS.get(current_user.country,current_user.state),{prompt: 'Select State...'} %>
			</div>
		<%end%>
	<p id="result"></p>
</div>
<script type="text/javascript">

$(document).ready(function() {
	$("#city1").change(function(){
		console.log($("#city").val())
		var city1 = $("#city").val()
		console.log(city1)
		$.ajax({
			url: "distance?city1="+city1, 
			type: 'GET',
			data: {
				 "city1": $("#city").val(),
				 "city2":"<%=@place.country%>"
			 },
			dataType: "json",
			success: function(response){
				var obj = JSON.stringify(response);
				$("#result").html("<b>the distance is "+obj+"</b>")
			}
		});
	});
});
</script>